version: '3'
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: app
        environment:
            APP_NAME: Application
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: laravel
        volumes:
            - .:/var/www
            - ./docker/php/debug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
        networks:
            - app-network
    db:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'db-data:/var/lib/mysql'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    db-data:
        driver: local
